"""The scripted cost map the integration proxy loads via LITELLM_MODEL_COST_MAP_URL (moved from cost_tracking_cases.json).

Plain JSON-shaped data: cost_tracking_case.py validates it into CostMapEntry and the scripted upstream serves it at /_cost_map."""

from typing import Final

from pydantic import JsonValue

COST_MAP_ENTRIES: Final[dict[str, dict[str, JsonValue]]] = {
    "dashscope/qwen4-max": {
        "litellm_provider": "dashscope",
        "mode": "chat",
        "max_input_tokens": 252000,
        "max_output_tokens": 65536,
        "tiered_pricing": [
            {"range": [0, 32000], "input_cost_per_token": 1.3e-06, "output_cost_per_token": 6.5e-06},
            {"range": [32000, 128000], "input_cost_per_token": 2.6e-06, "output_cost_per_token": 1.3e-05},
            {"range": [128000, 252000], "input_cost_per_token": 3.1e-06, "output_cost_per_token": 1.55e-05},
        ],
    },
    "gemini/gemini-3.8-flash-lite": {
        "litellm_provider": "gemini",
        "mode": "chat",
        "input_cost_per_token": 1.1e-07,
        "output_cost_per_token": 4.4e-07,
        "input_cost_per_token_above_128k_tokens": 2.2e-07,
        "output_cost_per_token_above_128k_tokens": 8.8e-07,
    },
    "openrouter/anthropic/claude-sonnet-5": {
        "litellm_provider": "openrouter",
        "mode": "chat",
        "input_cost_per_token": 3.2e-06,
        "output_cost_per_token": 1.6e-05,
    },
    "perplexity/sonar-next": {
        "litellm_provider": "perplexity",
        "mode": "chat",
        "input_cost_per_token": 1.13e-06,
        "output_cost_per_token": 1.05e-06,
        "search_context_cost_per_query": {
            "search_context_size_low": 0.005,
            "search_context_size_medium": 0.008,
            "search_context_size_high": 0.012,
        },
    },
    "perplexity/pplx-decider-v1-27b": {
        "input_cost_per_token": 4e-08,
        "litellm_provider": "perplexity",
        "max_input_tokens": 262144,
        "mode": "evaluation",
        "output_cost_per_token": 0.0,
    },
    "deepseek/deepseek-v4-chat": {
        "litellm_provider": "deepseek",
        "mode": "chat",
        "input_cost_per_token": 2.9e-07,
        "output_cost_per_token": 4.3e-07,
        "cache_read_input_token_cost": 2.9e-08,
        "cache_creation_input_token_cost": 0.0,
    },
    "xai/grok-5": {
        "litellm_provider": "xai",
        "mode": "chat",
        "input_cost_per_token": 1.35e-06,
        "output_cost_per_token": 2.7e-06,
        "cache_read_input_token_cost": 2.1e-07,
        "search_context_cost_per_query": {
            "search_context_size_low": 0.005,
            "search_context_size_medium": 0.005,
            "search_context_size_high": 0.005,
        },
    },
    "gpt-5.6": {
        "cache_read_input_token_cost": 1.75e-07,
        "input_cost_per_audio_token": 4e-05,
        "input_cost_per_token": 1.75e-06,
        "input_cost_per_token_flex": 8.75e-07,
        "input_cost_per_token_priority": 3.5e-06,
        "litellm_provider": "openai",
        "max_input_tokens": 400000,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_audio_token": 8e-05,
        "output_cost_per_reasoning_token": 1.6e-05,
        "output_cost_per_token": 1.4e-05,
        "output_cost_per_token_flex": 7e-06,
        "output_cost_per_token_priority": 2.8e-05,
        "search_context_cost_per_query": {
            "search_context_size_low": 0.01,
            "search_context_size_medium": 0.0125,
            "search_context_size_high": 0.015,
        },
        "supports_function_calling": True,
    },
    "gpt-5.4-mini": {
        "cache_read_input_token_cost": 3.5e-08,
        "input_cost_per_audio_token": 1e-05,
        "input_cost_per_token": 3.5e-07,
        "input_cost_per_token_flex": 1.75e-07,
        "input_cost_per_token_priority": 7e-07,
        "litellm_provider": "openai",
        "max_input_tokens": 400000,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_audio_token": 2e-05,
        "output_cost_per_reasoning_token": 3.2e-06,
        "output_cost_per_token": 2.8e-06,
        "output_cost_per_token_flex": 1.4e-06,
        "output_cost_per_token_priority": 5.6e-06,
        "search_context_cost_per_query": {
            "search_context_size_low": 0.01,
            "search_context_size_medium": 0.0125,
            "search_context_size_high": 0.015,
        },
        "supports_function_calling": True,
    },
    "azure/gpt-5.6": {
        "cache_read_input_token_cost": 1.8e-07,
        "input_cost_per_audio_token": 4.1e-05,
        "input_cost_per_token": 1.8e-06,
        "input_cost_per_token_flex": 9e-07,
        "input_cost_per_token_priority": 3.6e-06,
        "litellm_provider": "azure",
        "max_input_tokens": 400000,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_audio_token": 8.2e-05,
        "output_cost_per_reasoning_token": 1.65e-05,
        "output_cost_per_token": 1.44e-05,
        "output_cost_per_token_flex": 7.2e-06,
        "output_cost_per_token_priority": 2.88e-05,
        "search_context_cost_per_query": {
            "search_context_size_low": 0.01,
            "search_context_size_medium": 0.0125,
            "search_context_size_high": 0.015,
        },
        "supports_function_calling": True,
    },
    "azure/gpt-5.4-mini": {
        "cache_read_input_token_cost": 3.6e-08,
        "input_cost_per_audio_token": 1.05e-05,
        "input_cost_per_token": 3.6e-07,
        "input_cost_per_token_flex": 1.8e-07,
        "input_cost_per_token_priority": 7.2e-07,
        "litellm_provider": "azure",
        "max_input_tokens": 400000,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_audio_token": 2.1e-05,
        "output_cost_per_reasoning_token": 3.3e-06,
        "output_cost_per_token": 2.88e-06,
        "output_cost_per_token_flex": 1.44e-06,
        "output_cost_per_token_priority": 5.76e-06,
        "search_context_cost_per_query": {
            "search_context_size_low": 0.01,
            "search_context_size_medium": 0.0125,
            "search_context_size_high": 0.015,
        },
        "supports_function_calling": True,
    },
    "gpt-5.3-codex": {
        "cache_read_input_token_cost": 1.5e-07,
        "file_search_cost_per_1k_calls": 0.0025,
        "input_cost_per_token": 1.5e-06,
        "input_cost_per_token_flex": 7.5e-07,
        "input_cost_per_token_priority": 3e-06,
        "litellm_provider": "openai",
        "max_input_tokens": 400000,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "responses",
        "output_cost_per_reasoning_token": 1.3e-05,
        "output_cost_per_token": 1.2e-05,
        "output_cost_per_token_flex": 6e-06,
        "output_cost_per_token_priority": 2.4e-05,
        "search_context_cost_per_query": {
            "search_context_size_low": 0.01,
            "search_context_size_medium": 0.0125,
            "search_context_size_high": 0.015,
        },
        "supports_function_calling": True,
    },
    "gpt-5.5-pro": {
        "cache_read_input_token_cost": 1.5e-06,
        "file_search_cost_per_1k_calls": 0.0025,
        "input_cost_per_token": 1.5e-05,
        "input_cost_per_token_flex": 7.5e-06,
        "input_cost_per_token_priority": 3e-05,
        "litellm_provider": "openai",
        "max_input_tokens": 400000,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "responses",
        "output_cost_per_reasoning_token": 0.00013,
        "output_cost_per_token": 0.00012,
        "output_cost_per_token_flex": 6e-05,
        "output_cost_per_token_priority": 0.00024,
        "search_context_cost_per_query": {
            "search_context_size_low": 0.01,
            "search_context_size_medium": 0.0125,
            "search_context_size_high": 0.015,
        },
        "supports_function_calling": True,
    },
    "claude-opus-5": {
        "cache_creation_input_token_cost": 6.25e-06,
        "cache_creation_input_token_cost_above_1hr": 1e-05,
        "cache_creation_input_token_cost_above_200k_tokens": 1.25e-05,
        "cache_read_input_token_cost": 5e-07,
        "cache_read_input_token_cost_above_200k_tokens": 1e-06,
        "input_cost_per_token": 5e-06,
        "input_cost_per_token_above_200k_tokens": 1e-05,
        "input_cost_per_token_priority": 6.25e-06,
        "litellm_provider": "anthropic",
        "max_input_tokens": 400000,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_token": 2.5e-05,
        "output_cost_per_token_above_200k_tokens": 3.75e-05,
        "output_cost_per_token_priority": 3.125e-05,
        "provider_specific_entry": {"fast": 6.0, "us": 1.1},
        "search_context_cost_per_query": {"search_context_size_medium": 0.01},
        "supports_function_calling": True,
    },
    "claude-sonnet-5": {
        "cache_creation_input_token_cost": 3.75e-06,
        "cache_creation_input_token_cost_above_1hr": 6e-06,
        "cache_creation_input_token_cost_above_1hr_above_200k_tokens": 1.2e-05,
        "cache_creation_input_token_cost_above_200k_tokens": 7.5e-06,
        "cache_read_input_token_cost": 3e-07,
        "cache_read_input_token_cost_above_200k_tokens": 6e-07,
        "input_cost_per_token": 3e-06,
        "input_cost_per_token_above_200k_tokens": 6e-06,
        "input_cost_per_token_priority": 3.75e-06,
        "litellm_provider": "anthropic",
        "max_input_tokens": 400000,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_token": 1.5e-05,
        "output_cost_per_token_above_200k_tokens": 2.25e-05,
        "output_cost_per_token_priority": 1.875e-05,
        "provider_specific_entry": {"us": 1.1},
        "search_context_cost_per_query": {"search_context_size_medium": 0.01},
        "supports_function_calling": True,
    },
    "claude-haiku-4-5": {
        "cache_creation_input_token_cost": 1.25e-06,
        "cache_creation_input_token_cost_above_1hr": 2e-06,
        "cache_read_input_token_cost": 1e-07,
        "input_cost_per_token": 1e-06,
        "input_cost_per_token_priority": 1.25e-06,
        "litellm_provider": "anthropic",
        "max_input_tokens": 400000,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_token": 5e-06,
        "output_cost_per_token_priority": 6.25e-06,
        "provider_specific_entry": {"us": 1.1},
        "search_context_cost_per_query": {"search_context_size_medium": 0.01},
        "supports_function_calling": True,
    },
    "us.anthropic.claude-opus-5-v1:0": {
        "cache_creation_input_token_cost": 6.875e-06,
        "cache_creation_input_token_cost_above_1hr": 1.1e-05,
        "cache_creation_input_token_cost_above_200k_tokens": 1.375e-05,
        "cache_read_input_token_cost": 5.5e-07,
        "cache_read_input_token_cost_above_200k_tokens": 1.1e-06,
        "input_cost_per_token": 5.5e-06,
        "input_cost_per_token_above_200k_tokens": 1.1e-05,
        "input_cost_per_token_flex": 2.75e-06,
        "input_cost_per_token_priority": 6.875e-06,
        "litellm_provider": "bedrock_converse",
        "max_input_tokens": 400000,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_token": 2.75e-05,
        "output_cost_per_token_above_200k_tokens": 4.125e-05,
        "output_cost_per_token_flex": 1.375e-05,
        "output_cost_per_token_priority": 3.4375e-05,
        "supports_function_calling": True,
    },
    "anthropic.claude-sonnet-5-v1:0": {
        "cache_creation_input_token_cost": 4.125e-06,
        "cache_creation_input_token_cost_above_1hr": 6.6e-06,
        "cache_read_input_token_cost": 3.3e-07,
        "input_cost_per_token": 3.3e-06,
        "input_cost_per_token_flex": 1.65e-06,
        "input_cost_per_token_priority": 4.125e-06,
        "litellm_provider": "bedrock_converse",
        "max_input_tokens": 400000,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_token": 1.65e-05,
        "output_cost_per_token_flex": 8.25e-06,
        "output_cost_per_token_priority": 2.0625e-05,
        "supports_function_calling": True,
    },
    "meta.llama4-maverick-17b-instruct-v1:0": {
        "input_cost_per_token": 2.4e-07,
        "litellm_provider": "bedrock_converse",
        "max_input_tokens": 400000,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_token": 9.7e-07,
        "supports_function_calling": True,
    },
    "gemini/gemini-3.1-pro": {
        "cache_read_input_token_cost": 2e-07,
        "cache_read_input_token_cost_above_200k_tokens": 4e-07,
        "google_maps_grounding_cost_per_query": 0.025,
        "input_cost_per_audio_token": 2.6e-06,
        "input_cost_per_image_token": 2.2e-06,
        "input_cost_per_token": 2e-06,
        "input_cost_per_token_above_200k_tokens": 4e-06,
        "input_cost_per_token_flex": 1e-06,
        "input_cost_per_token_priority": 2.5e-06,
        "input_cost_per_video_token": 2.4e-06,
        "litellm_provider": "gemini",
        "max_input_tokens": 1048576,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_reasoning_token": 1.3e-05,
        "output_cost_per_token": 1.2e-05,
        "output_cost_per_token_above_200k_tokens": 1.8e-05,
        "output_cost_per_token_flex": 6e-06,
        "output_cost_per_token_priority": 1.5e-05,
        "search_context_cost_per_query": {"search_context_size_medium": 0.035},
        "supports_function_calling": True,
        "web_search_billing_unit": "per_query",
    },
    "gemini/gemini-3.8-flash": {
        "cache_read_input_token_cost": 5e-08,
        "google_maps_grounding_cost_per_query": 0.025,
        "input_cost_per_audio_token": 1e-06,
        "input_cost_per_image_token": 5.5e-07,
        "input_cost_per_token": 5e-07,
        "input_cost_per_token_flex": 2.5e-07,
        "input_cost_per_token_priority": 6.25e-07,
        "input_cost_per_video_token": 6e-07,
        "litellm_provider": "gemini",
        "max_input_tokens": 1048576,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_audio_token": 6e-06,
        "output_cost_per_reasoning_token": 3.5e-06,
        "output_cost_per_token": 3e-06,
        "output_cost_per_token_flex": 1.5e-06,
        "output_cost_per_token_priority": 3.75e-06,
        "search_context_cost_per_query": {"search_context_size_medium": 0.035},
        "supports_function_calling": True,
        "web_search_billing_unit": "per_prompt",
    },
    "gemini-3.1-pro": {
        "cache_read_input_token_cost": 2.1e-07,
        "cache_read_input_token_cost_above_200k_tokens": 4.2e-07,
        "google_maps_grounding_cost_per_query": 0.025,
        "input_cost_per_audio_token": 2.7e-06,
        "input_cost_per_image_token": 2.3e-06,
        "input_cost_per_token": 2.1e-06,
        "input_cost_per_token_above_200k_tokens": 4.2e-06,
        "input_cost_per_token_flex": 1.05e-06,
        "input_cost_per_token_priority": 2.625e-06,
        "litellm_provider": "vertex_ai-language-models",
        "max_input_tokens": 1048576,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_reasoning_token": 1.35e-05,
        "output_cost_per_token": 1.26e-05,
        "output_cost_per_token_above_200k_tokens": 1.89e-05,
        "output_cost_per_token_flex": 6.3e-06,
        "output_cost_per_token_priority": 1.575e-05,
        "search_context_cost_per_query": {"search_context_size_medium": 0.035},
        "supports_function_calling": True,
        "web_search_billing_unit": "per_query",
    },
    "gemini-3.8-flash": {
        "cache_read_input_token_cost": 5.2e-08,
        "google_maps_grounding_cost_per_query": 0.025,
        "input_cost_per_audio_token": 1.04e-06,
        "input_cost_per_token": 5.2e-07,
        "input_cost_per_token_flex": 2.6e-07,
        "input_cost_per_token_priority": 6.5e-07,
        "input_cost_per_video_token": 6.2e-07,
        "litellm_provider": "vertex_ai-language-models",
        "max_input_tokens": 1048576,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_audio_token": 6.24e-06,
        "output_cost_per_token": 3.12e-06,
        "output_cost_per_token_flex": 1.56e-06,
        "output_cost_per_token_priority": 3.9e-06,
        "search_context_cost_per_query": {"search_context_size_medium": 0.035},
        "supports_function_calling": True,
        "web_search_billing_unit": "per_prompt",
    },
    "together_ai/moonshotai/Kimi-K3": {
        "input_cost_per_token": 1.15e-06,
        "litellm_provider": "together_ai",
        "max_input_tokens": 400000,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_token": 3.45e-06,
        "supports_function_calling": True,
    },
    "together_ai/zai-org/GLM-5.3": {
        "input_cost_per_token": 5.5e-07,
        "litellm_provider": "together_ai",
        "max_input_tokens": 400000,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_token": 2.2e-06,
        "supports_function_calling": True,
    },
    "fireworks_ai/accounts/fireworks/models/kimi-k3": {
        "cache_read_input_token_cost": 6e-08,
        "input_cost_per_token": 6e-07,
        "litellm_provider": "fireworks_ai",
        "max_input_tokens": 400000,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_token": 2.5e-06,
        "supports_function_calling": True,
    },
    "fireworks_ai/accounts/fireworks/models/deepseek-v4p1-flash": {
        "input_cost_per_token": 1.5e-07,
        "litellm_provider": "fireworks_ai",
        "max_input_tokens": 400000,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_token": 6e-07,
        "supports_function_calling": True,
    },
    "fireworks_ai/accounts/fireworks/models/qwen3p8-max": {
        "cache_read_input_token_cost": 9e-08,
        "input_cost_per_token": 9e-07,
        "litellm_provider": "fireworks_ai",
        "max_input_tokens": 400000,
        "max_output_tokens": 65536,
        "max_tokens": 65536,
        "mode": "chat",
        "output_cost_per_token": 3.6e-06,
        "supports_function_calling": True,
    },
    "whisper-next": {"litellm_provider": "openai", "mode": "audio_transcription", "input_cost_per_second": 0.0001},
    "whisper-verbose-next": {
        "litellm_provider": "openai",
        "mode": "audio_transcription",
        "input_cost_per_second": 0.0002,
    },
    "gpt-4o-transcribe-next": {
        "litellm_provider": "openai",
        "mode": "audio_transcription",
        "input_cost_per_token": 2.11e-06,
        "output_cost_per_token": 3.11e-06,
        "input_cost_per_audio_token": 1e-05,
    },
    "nova-next": {"litellm_provider": "deepgram", "mode": "audio_transcription", "input_cost_per_second": 0.0003},
    "azure/whisper-next": {
        "litellm_provider": "azure",
        "mode": "audio_transcription",
        "input_cost_per_second": 0.00011,
    },
    "tts-next": {"litellm_provider": "openai", "mode": "audio_speech", "input_cost_per_character": 1e-05},
    "tts-next-hd": {"litellm_provider": "openai", "mode": "audio_speech", "input_cost_per_character": 2e-05},
    "azure/tts-next": {"litellm_provider": "azure", "mode": "audio_speech", "input_cost_per_character": 1.1e-05},
    "gpt-image-next": {
        "litellm_provider": "openai",
        "mode": "image_generation",
        "input_cost_per_token": 1.71e-06,
        "output_cost_per_token": 4.3e-06,
        "input_cost_per_image_token": 2.2e-06,
        "output_cost_per_image_token": 5.1e-06,
    },
    "1024-x-1024/dall-e-3-next": {
        "litellm_provider": "openai",
        "mode": "image_generation",
        "input_cost_per_image": 0.04,
    },
    "hd/1024-x-1024/dall-e-3-next": {
        "litellm_provider": "openai",
        "mode": "image_generation",
        "input_cost_per_image": 0.08,
    },
    "1792-x-1024/dall-e-3-next": {
        "litellm_provider": "openai",
        "mode": "image_generation",
        "input_cost_per_image": 0.06,
    },
    "low/1024-x-1024/gpt-image-next": {
        "litellm_provider": "openai",
        "mode": "image_generation",
        "input_cost_per_token": 1.7e-06,
        "output_cost_per_token": 4.3e-06,
        "input_cost_per_image_token": 2.2e-06,
        "output_cost_per_image_token": 5.1e-06,
    },
    "1024-x-1024/imagen-next": {
        "litellm_provider": "vertex_ai-image-models",
        "mode": "image_generation",
        "output_cost_per_image": 0.05,
    },
    "amazon.nova-canvas-next": {
        "litellm_provider": "bedrock",
        "mode": "image_generation",
        "output_cost_per_image": 0.045,
    },
    "bedrock/invoke/anthropic.claude-haiku-4-5-20251001-v1:0": {
        "litellm_provider": "bedrock",
        "mode": "chat",
        "input_cost_per_token": 1.19e-06,
        "output_cost_per_token": 5.01e-06,
    },
    "eu.anthropic.claude-sonnet-5-v1:0": {
        "litellm_provider": "bedrock_converse",
        "mode": "chat",
        "input_cost_per_token": 3.4e-06,
        "output_cost_per_token": 1.7e-05,
    },
    "amazon.nova-2-pro-preview-20251202-v1:0": {
        "litellm_provider": "bedrock_converse",
        "mode": "chat",
        "input_cost_per_token": 2.1875e-06,
        "output_cost_per_token": 1.75e-05,
    },
    "mistral.mistral-large-3-675b-instruct": {
        "litellm_provider": "bedrock_converse",
        "mode": "chat",
        "input_cost_per_token": 5.1e-07,
        "output_cost_per_token": 1.51e-06,
    },
    "azure_ai/gpt-5.4-mini-2026-03-17": {
        "litellm_provider": "azure_ai",
        "mode": "chat",
        "input_cost_per_token": 7.5e-07,
        "output_cost_per_token": 4.5e-06,
    },
    "groq/qwen/qwen3.8-27b": {
        "litellm_provider": "groq",
        "mode": "chat",
        "input_cost_per_token": 8e-07,
        "output_cost_per_token": 4e-06,
    },
    "cohere_chat/v2/command-a-03-2025": {
        "litellm_provider": "cohere_chat",
        "mode": "chat",
        "input_cost_per_token": 2.51e-06,
        "output_cost_per_token": 1.001e-05,
    },
    "mistral/mistral-medium-2604": {
        "litellm_provider": "mistral",
        "mode": "chat",
        "input_cost_per_token": 1.51e-06,
        "output_cost_per_token": 7.51e-06,
    },
    "text-embedding-3-large": {"litellm_provider": "openai", "mode": "embedding", "input_cost_per_token": 1.3e-07},
    "gpt-5.4": {
        "litellm_provider": "openai",
        "mode": "chat",
        "input_cost_per_token": 2.5e-06,
        "output_cost_per_token": 1.5e-05,
        "cache_read_input_token_cost": 2.5e-07,
        "input_cost_per_token_batches": 1.25e-06,
        "output_cost_per_token_batches": 7.5e-06,
    },
    "gpt-realtime-mini-2025-12-15": {
        "litellm_provider": "openai",
        "mode": "realtime",
        "input_cost_per_token": 6e-07,
        "output_cost_per_token": 2.4e-06,
        "input_cost_per_audio_token": 1e-05,
        "cache_read_input_token_cost": 6e-08,
        "cache_read_input_audio_token_cost": 3e-07,
        "output_cost_per_audio_token": 2e-05,
    },
    "gpt-realtime-2.1": {
        "litellm_provider": "openai",
        "mode": "realtime",
        "input_cost_per_token": 4e-06,
        "input_cost_per_audio_token": 3.2e-05,
        "cache_read_input_token_cost": 4e-07,
        "cache_read_input_audio_token_cost": 4e-07,
        "output_cost_per_token": 2.4e-05,
        "output_cost_per_audio_token": 6.4e-05,
    },
    "text-embedding-4-small": {
        "input_cost_per_token": 1.01e-06,
        "output_cost_per_token": 0,
        "litellm_provider": "openai",
        "mode": "embedding",
    },
    "text-embedding-3-large-next": {
        "input_cost_per_token": 1.02e-06,
        "output_cost_per_token": 0,
        "litellm_provider": "openai",
        "mode": "embedding",
    },
    "azure/text-embedding-4-large": {
        "input_cost_per_token": 1.03e-06,
        "output_cost_per_token": 0,
        "litellm_provider": "azure",
        "mode": "embedding",
    },
    "embed-v5": {
        "input_cost_per_token": 1.04e-06,
        "output_cost_per_token": 0,
        "litellm_provider": "cohere",
        "mode": "embedding",
    },
    "amazon.titan-embed-text-v2:0": {
        "input_cost_per_token": 1.05e-06,
        "output_cost_per_token": 0,
        "litellm_provider": "bedrock",
        "mode": "embedding",
    },
    "cohere.embed-english-v4": {
        "input_cost_per_token": 1.06e-06,
        "output_cost_per_token": 0,
        "litellm_provider": "bedrock",
        "mode": "embedding",
    },
    "text-embedding-006": {
        "input_cost_per_token": 1.07e-06,
        "output_cost_per_token": 0,
        "litellm_provider": "vertex_ai-embedding-models",
        "mode": "embedding",
    },
    "gemini/gemini-embedding-002": {
        "input_cost_per_token": 1.08e-06,
        "output_cost_per_token": 0,
        "litellm_provider": "gemini",
        "mode": "embedding",
    },
    "together_ai/together-embed-v1": {
        "input_cost_per_token": 1.09e-06,
        "output_cost_per_token": 0,
        "litellm_provider": "together_ai",
        "mode": "embedding",
    },
    "fireworks_ai/fireworks-embed-v1": {
        "input_cost_per_token": 1.1e-06,
        "output_cost_per_token": 0,
        "litellm_provider": "fireworks_ai",
        "mode": "embedding",
    },
    "rerank-v4": {
        "input_cost_per_token": 1.11e-06,
        "output_cost_per_token": 0,
        "input_cost_per_query": 0.0021,
        "litellm_provider": "cohere",
        "mode": "rerank",
    },
    "cohere.rerank-v4:0": {
        "input_cost_per_token": 1.12e-06,
        "output_cost_per_token": 0,
        "input_cost_per_query": 0.0022,
        "litellm_provider": "bedrock",
        "mode": "rerank",
    },
    "gpt-3.5-turbo-instruct-next": {
        "input_cost_per_token": 1.14e-06,
        "output_cost_per_token": 2.14e-06,
        "litellm_provider": "text-completion-openai",
        "mode": "completion",
    },
    "omni-moderation-next": {
        "input_cost_per_token": None,
        "output_cost_per_token": 0,
        "litellm_provider": "openai",
        "mode": "moderation",
    },
    "together_ai/meta-llama/Llama-3.3-70B-Instruct-Turbo": {
        "input_cost_per_token": 1.16e-06,
        "output_cost_per_token": 2.16e-06,
        "litellm_provider": "together_ai",
        "mode": "completion",
    },
    "gemini/gemini-nano-banana-2.1": {
        "input_cost_per_token": 1.5e-06,
        "input_cost_per_token_batches": 7.5e-07,
        "litellm_provider": "gemini",
        "max_input_tokens": 131072,
        "max_output_tokens": 32768,
        "max_tokens": 32768,
        "mode": "image_generation",
        "output_cost_per_image": 0.0336,
        "output_cost_per_image_token": 3e-05,
        "output_cost_per_token": 7.5e-06,
        "output_cost_per_token_batches": 3.75e-06,
        "search_context_cost_per_query": {
            "search_context_size_high": 0.014,
            "search_context_size_low": 0.014,
            "search_context_size_medium": 0.014,
        },
        "web_search_billing_unit": "per_query",
    },
    "xai/grok-4.7": {
        "litellm_provider": "xai",
        "mode": "chat",
        "input_cost_per_token": 2e-06,
        "output_cost_per_token": 6e-06,
        "cache_read_input_token_cost": 5e-07,
        "max_tokens": 500000,
        "max_input_tokens": 500000,
        "max_output_tokens": 500000,
        "supports_function_calling": True,
    },
    "us.anthropic.claude-opus-5-5": {
        "litellm_provider": "bedrock_converse",
        "mode": "chat",
        "input_cost_per_token": 4.4e-06,
        "output_cost_per_token": 2.2e-05,
        "cache_read_input_token_cost": 2.2e-07,
        "cache_creation_input_token_cost": 5.5e-06,
        "max_tokens": 128000,
        "max_input_tokens": 1000000,
        "max_output_tokens": 128000,
        "supports_function_calling": True,
    },
    "claude-opus-5-5": {
        "litellm_provider": "anthropic",
        "mode": "chat",
        "input_cost_per_token": 4e-06,
        "output_cost_per_token": 2e-05,
        "cache_read_input_token_cost": 2e-07,
        "cache_creation_input_token_cost": 5e-06,
        "max_tokens": 128000,
        "max_input_tokens": 1000000,
        "max_output_tokens": 128000,
        "supports_function_calling": True,
    },
    "gpt-6.1-sol": {
        "litellm_provider": "openai",
        "mode": "chat",
        "input_cost_per_token": 2e-06,
        "output_cost_per_token": 1e-05,
        "cache_read_input_token_cost": 1e-07,
        "max_tokens": 128000,
        "max_input_tokens": 922000,
        "max_output_tokens": 128000,
        "supports_function_calling": True,
    },
}
